### PR TITLE
Change section in index.html, basic style in CSS.

### PR DESCRIPTION
**Pull request by soniawu**
I made some change on basic style, font family, size, margin and padding. I use 16 px minor third (1.2) as the html font. Also the silver color is added for the info block. Please review it and give your comments.

Thank you.

### CODE REVIEW

**Comment by mjachna** [comment]
for this line:
line-height: 1.2em; /* 1.2 grid line, 39.814px 1.2em @ 33.178px */
shouldnt it be  this:  
line-height: 1.157em /* 2 grid lines, 38.4 / 33.178 = 1.157em*/

**Comment by soniawu** [comment]
I am note sure what the grid line should based on. I know you base on the html line-height 19.2, it's 2. I base on the h1 font-size, it's 1.2. We can clear it out late. But line-height is designed by developer for a comfortable visual effect. Can you use this on your desktop layout now? If you find out it's more comfortable to use smaller line-height, it's fine to change to the suggested number or other better number.

Thank you.

**Comment by mjachna** [comment]
If you look at the professors previous work he took the original line height and multiplied it until it was larger then the font size then just divided line height by fontsize to get the em's to keep a uniform layout. We can discusse this later, I'll add this for now and work on the larger desktop version.

**Comment by soniawu** [comment]
I agree I am confused on this part. I will watch the video again when I have time. Thank you.

**Pull request merged**
